---
title: "Things that look like coordinates"
author: "Simon Goring"
date: "April 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Coordinates

What actually looks like a set of coordinates?  This is a small Rmd to help us look for different coordinate sets and then apply the regex across all of them (or some of them).

```{r load_packages, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
devtools::install_github('EarthCubeGeochron/geodiveR')

library(geodiveR)

library(jsonlite)
library(readr)
library(dplyr)
library(stringr)
library(leaflet)
library(purrr)
library(DT)
library(assertthat)

sourcing <- list.files('R', full.names = TRUE) %>% 
  map(source, echo = FALSE, print = FALSE, verbose = FALSE)

publications <- fromJSON(txt = 'input/bibjson', flatten = TRUE)
full_nlp <- readr::read_tsv('input/sentences_nlp352', 
                       trim_ws = TRUE,
                       col_names = c('_gddid', 'sentence', 'wordIndex', 
                                     'word', 'partofspeech', 'specialclass', 
                                     'wordsAgain', 'wordtype', 'wordmodified'))

nlp_clean <- clean_corpus(x = full_nlp, pubs = publications) #uses the clean_corpus.R function

nlp <- nlp_clean$nlp

```

We've established some basic regex to try to pull coordinates.

```{r broad_coords, echo=TRUE, message=FALSE}

loose_coord <- "(([,-]\\d{1,3}[^a-zA-Z0-9]{1,4}\\d+?.{1,7}){1,4})([NESWnesw]?),"

lmatch <- stringr::str_detect(nlp$word, loose_coord)

browse(lmatch, corpus = nlp, pubs = publications)

```

